/*
 * data_display_thread.c
 *
 * this is a thread that pulls the data generated by another thread from a
 * mail queue and then displays it in a terminal
 *
 * author:    Dr. Alex Shenfield
 * date:      22/10/2021
 * purpose:   55-604481 embedded computer networks - lab 103
 */

// include the c standard io library
#include <stdio.h>

// include cmsis_os for the rtos api
#include "cmsis_os2.h"

// include my rtos objects
#include "rtos_objects.h"

// include the shu bsp libraries for the stm32f7 discovery board
#include "pinmappings.h"
#include "clock.h"
#include "random_numbers.h"
#include "gpio.h"

// ACTUAL THREADS

// data display thread - pull the data out of the mail queue and print it to
// the uart
void data_display(void const *argument)
{
  // print a status message
  printf("display thread up and running ...\r\n");

  // initialise our message object and the message priority
  message_t msg;
  uint8_t   priority;

  // infinite loop getting out fake data ...
  while(1)
  {
    // get the next message in the queue
    osStatus_t status = osMessageQueueGet(m_messages, &msg, &priority, osWaitForever);
    if(status == osOK)
    {
      // print it to the serial terminal
      printf("\r\n");
      printf("Voltage: %.2f V\r\n", msg.voltage);
      printf("Current: %.2f A\r\n", msg.current);
      printf("Number of cycles: %u\r\n", msg.counter);
    }
  }
}
